# Generated by Django 2.2.19 on 2022-11-13 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('Купля-продажа', (('b', 'Куплю'), ('s', 'Продам'))), ('Обмен', (('с', 'Обменяю'),))], default='s', max_length=1, verbose_name='Продам/Куплю'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Неправильное название товара'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар'),
        ),
    ]
